### PR TITLE
Breguet range

### PR DESCRIPTION
**Pull request by mjburton11**
Got rid of Mach number, added velocity

### CODE REVIEW

**Comment by whoburg** [comment]
Is the intent of this PR to change Mach number to Velocity? I propose we cherry-pick the relevant commit (b65e3b470b14353700b8aacec6c61734477d5970), since RvsC.ipynb is broken on this branch. If that sounds good, just let me know, and I'll do it.

**Comment by mjburton11** [comment]
Yes, I just wanted to push the change of mach to velocity.  So that would be great if you could cherry pick it.

**Comment by mjburton11** [comment]
Where should I put `RvsC.ipynb`?

**Comment by whoburg** [comment]
Ok, b65e3b470b14353700b8aacec6c61734477d5970 has been cherry-picked to master.

**Comment by whoburg** [comment]
Re: RvsC.ipynb, is this a model you expect others might use, or more of a demo? I'd say that if it is working perhaps we could throw it in an examples folder?

**Comment by mjburton11** [comment]
So `RvsC.ipyny` was just a demo.  The only thing that is not working is the interactive stuff.  So we could put the actual GP part in the examples folder if you want.

**Pull request closed without merging**
