### PR TITLE
object model of solar UAV

### PR DESCRIPTION
**Pull request by bqpd**
#5 as an object model

### CODE REVIEW

**Comment by bqpd** [comment]
It's just indented with an extra line of class declaration. Can now be merged with wing models, etc (if C_L, C_D are taken out of their current grouping.

**Comment by bqpd** [comment]
In 215fd6c it's adapted to use Var instead of Variable and no kwargs in Var declarations

**Comment by bqpd** [comment]
(I'm wondering if Var should be our default name? It is nicely short...especially for use with `gpkit.`)

**Comment by whoburg** [comment]
Looks great. I don't think I'm ready to move from `Variable` to `Var` (unless we do it across GPkit, which would be well outside scope of this PR). (My justification: I see value in having one name, and only one name, for each class, across the code base.)

I added one commit that reverts that change but keeps the removal of the keyword args.

@bqpd, I'm ready to merge this if you are too.

**Comment by bqpd** [comment]
Yup!

**Pull request merged**
